server.port: 8082
spring:
  application:
    name: shopping-app
  # security:
  #   user:
  #     name: root
  #     password: root
  #   oauth2:
  #     client:
  #       registration:
  #         # github:
  #         #   clientId: Ov23liiYwb6S4Cg0U02d
  #         #   clientSecret: 4317b8ccb72d7ce879e8d887e5705a1fc9e32d15
  #         google:
  #           clientId: 392652762784-ssi8llseno3mg97cjaspj4hkccfoo05i.apps.googleusercontent.com
  #           clientSecret: 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
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_app?allowPublicKeyRetrieval=true&useSSL=false
    username: springstudent
    password: springstudent
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
  # Hibernate Properties
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  # session:
  #   store-type: jdbc
# server:
#   servlet:
#     session:
#       cookie:
#         name: JSESSIONID
#         path: /
#         http-only: true
#         secure: true

logging.config: classpath:log4j2.xml
logging.level.root: info
